### ISSUE TITLE
Review open PR

### ISSUE THREAD

**Issue by pankajastro** [astronomer/dag-factory#203]
Review the below PRs

- [x]  https://github.com/astronomer/dag-factory/pull/184 - most important one (synced with @cmarteepants )
- [x] - https://github.com/astronomer/dag-factory/pull/174
- [x] - https://github.com/astronomer/dag-factory/pull/218
- [x] - https://github.com/astronomer/dag-factory/pull/103
- [x] - https://github.com/astronomer/dag-factory/pull/88

Merge at least two of them.

**Comment by pankajkoti** [comment]
Looks like the scope of this issue is achieved. Good to close this issue @tatiana @pankajastro ?
