### ISSUE TITLE
Increase project quality

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/dag-factory#206]
Description co-authored by @tatiana @pankajastro

Scope:
- [x] https://github.com/astronomer/dag-factory/issues/199
- [x] https://github.com/astronomer/dag-factory/issues/198
- [x] https://github.com/astronomer/dag-factory/issues/196
- [x] https://github.com/astronomer/dag-factory/issues/197
- [x] #230

**Comment by matveykortsev** [comment]
Guys add please support for on_failure_callback in this way:
```
from airflow.providers.slack.notifications.slack import send_slack_notification
'on_failure_callback': [
        send_slack_notification(
            slack_conn_id='slack',
            text="""
                :red_circle: Task Failed. 
                *Task*: {{ ti.task_id }}  
                *Dag*: {{ ti.dag_id }} 
                *Execution Time*: {{ ti.execution_date }}  
                *Log Url*: {{ ti.log_url }} 
                """,
            channel="analytics-alerts",
            username="Airflow",
        )
    ],
```
Now its only possible without params and only through absolute path for .py file.

**Comment by pankajastro** [comment]
Thank you, @matveykortsev, indeed, this feature would be valuable. I've created a high-level task to compare the missing issues like this.
