### ISSUE TITLE
[telemetry] Identify a better strategy of when to emit telemetry

### ISSUE THREAD

**Issue by tatiana** [astronomer/dag-factory#282]
As of DAG Factory 0.20, we emit user activity events every time a DAG Factory DAG is parsed, as part of #250.

Tracking when a DAG is parsed does not seem to provide much value. Would there be better ways to track usage if the DAG factory was installed in remote hosts?

One possibility, for instance, is to use Airflow listeners and only emit events before or after a DAG Factory-build DAG is run: https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/listeners.html.

The goal of this ticket is to brainstorm possibilities and improve our current approach.

**Comment by pankajastro** [comment]
> Tracking when a DAG is parsed doesn't seem to provide much value.

Currently, we collect `dags_count`, `tasks_count`, and `taskgroups_count`. I wanted to understand what additional data might help us. Are we looking for runtime data like `DagRun`? Could you please elaborate a bit?

I explored the Airflow listener, and I think if information like `DagRun` would be helpful, we could consider implementing a custom solution using `on_dag_run_running` listener to emit an event when a DagRun belongs to a DagFactory DAG. We could see if we can attach some parameters to the DAG to accurately identify if the DAG is from DagFactory

**Comment by tatiana** [comment]
Currently, whenever these things are currently called:
- DagBuilder
- load_yaml_dags

We emit the events. (dags_count, task_count)

We emit this information every time these things are called during DAG parsing (let's say every 30 seconds).

From a telemetry perspective, the data we're collecting is proportional to the number of times the DAG is parsed. But from a business perspective, this is not so meaningful.

Some examples of what would be more valuable business metrics:
1. In an Airflow deployment: how many dags and tasks are created with DAG Factory (once, per deployment)
2. How many DAG runs are from DAGs created with DAG Factory (successful / failure)
3. How many task runs are from tasks created via DAG Factory (successful / failure)

With the listeners' approach, we could collect/emit (2) and (3) by installing the plugin:
https://github.com/astronomer/astronomer-cosmos/blob/1abb37145fcc3b756c513a60f04a659491d84761/pyproject.toml#L104-L108

We may not want to worry about (1) as a starting point - by replacing the current DAG-parsing-focused approach with the listeners' approach, we may already have much more valuable information.
