### ISSUE TITLE
SubDag Support

### ISSUE THREAD

**Issue by Naraujo13** [astronomer/dag-factory#63]
Hey!

I was testing some use cases to use it at our company, and was wondering if there is any support for SubDag operator?
I played around a bit and couldn't make it work.

Congrats on the great lib.

Cheers

**Comment by ajbosco** [comment]
I haven't tried to use SubDags with`dag-factory` yet, but I don't see why it couldn't be extended to handle them if it doesn't work now. I'll see if I can tackle it soon.

**Comment by tatiana** [comment]
SubDags have been deprecated since Airflow 2.0 and will be removed in AIrflow 3, so we should not invest in this area.
